### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [dsoastro/framebuffer_driver_rpi#1]
Hello!

I found link to this project from https://habr.com/ru/post/536110/

Could you please add information about license of this repository — is it allowed to copy, change and use the code in any purpose?
It would be great to see any popular open source license.

If this code is based on Linux kernel, then GPL v2 should be the best.

**Comment by dsoastro** [comment]
Added license terms to README.md

**Comment by vazhnov** [comment]
GPL v2 — great, thank you!
